import { useState } from 'react';
import { AGENT_RULES, WIRE_FORMAT_NOTES, type AgentRule } from '../data/agent-guide';
import { CodeBlock } from '../components/CodeBlock';

export function AgentGuideSection() {
  const [activeRule, setActiveRule] = useState<AgentRule>(AGENT_RULES[0]);

  return (
    <div>
      <div className="mb-8">
        <div className="inline-flex items-center gap-2 px-3 py-1.5 rounded-full bg-primary-50 border border-primary-200 text-primary-700 text-xs font-semibold mb-4">
          <span className="w-1.5 h-1.5 rounded-full bg-primary-500 animate-pulse"></span>
          For AI Agents
        </div>
        <h1 className="section-title">Agent Guide</h1>
        <p className="section-desc">
          Rules, gotchas, and patterns that AI agents must follow when generating journeys with the SDK. Every rule
          here corresponds to a real failure mode observed in production journeys.
        </p>
      </div>

      {/* Rules */}
      <h2 className="text-xl font-bold text-gray-900 mb-4">Rules & Gotchas</h2>
      <div className="flex flex-col md:flex-row gap-4 md:gap-6 mb-8 sm:mb-14">
        {/* Rule list */}
        <div className="md:w-64 flex-shrink-0">
          <div className="flex md:flex-col gap-1 overflow-x-auto md:overflow-x-visible pb-2 md:pb-0">
            {AGENT_RULES.map((rule, i) => (
              <button
                key={i}
                onClick={() => setActiveRule(rule)}
                className={`text-left px-3 py-2.5 rounded-xl text-sm transition-all whitespace-nowrap md:whitespace-normal md:w-full ${
                  activeRule.title === rule.title
                    ? 'bg-primary-50 text-primary-700 font-semibold border border-primary-200'
                    : 'text-gray-500 hover:bg-gray-50 hover:text-gray-700'
                }`}
              >
                <span className="text-gray-300 text-xs font-mono mr-2">{String(i + 1).padStart(2, '0')}</span>
                {rule.title}
              </button>
            ))}
          </div>
        </div>

        {/* Rule detail */}
        <div className="flex-1 min-w-0 space-y-4">
          <div className="card">
            <h3 className="font-bold text-gray-900 text-base mb-2">{activeRule.title}</h3>
            <p className="text-sm text-gray-600 leading-relaxed">{activeRule.explanation}</p>
          </div>

          {activeRule.bad && (
            <div>
              <div className="flex items-center gap-2 mb-2">
                <span className="w-5 h-5 rounded-full bg-red-100 text-red-600 text-xs flex items-center justify-center font-bold">✕</span>
                <span className="text-xs font-bold text-red-600 uppercase tracking-wide">Avoid</span>
              </div>
              <CodeBlock code={activeRule.bad} language="typescript" />
            </div>
          )}

          {activeRule.good && (
            <div>
              <div className="flex items-center gap-2 mb-2">
                <span className="w-5 h-5 rounded-full bg-emerald-100 text-emerald-600 text-xs flex items-center justify-center font-bold">✓</span>
                <span className="text-xs font-bold text-emerald-600 uppercase tracking-wide">Do this</span>
              </div>
              <CodeBlock code={activeRule.good} language="typescript" />
            </div>
          )}
        </div>
      </div>

      {/* Wire format quick reference */}
      <h2 className="text-xl font-bold text-gray-900 mb-1">Wire Format Quick Reference</h2>
      <p className="text-sm text-gray-400 mb-4 sm:mb-5">Key fields in every v3 uischema element and what they mean</p>
      <div className="grid grid-cols-1 md:grid-cols-2 gap-3 mb-8 sm:mb-14">
        {WIRE_FORMAT_NOTES.map((note) => (
          <div key={note.field} className="bg-white border border-gray-100 rounded-xl p-4">
            <p className="font-mono text-sm text-primary-700 font-semibold mb-1">{note.field}</p>
            <p className="text-xs text-gray-500 leading-relaxed">{note.note}</p>
          </div>
        ))}
      </div>

      {/* Anatomy of a block */}
      <h2 className="text-xl font-bold text-gray-900 mb-4">Anatomy of a Block (v3 Wire Format)</h2>
      <CodeBlock
        title="Every block element shape"
        language="json"
        code={`{
  "id": "a1b2c3d4-...",          // UUID, auto-generated by createBlock()
  "type": "PersonalInformationControl",  // ControlName constant
  "scope": "#/properties/pi",   // "#/properties/" + block name
  "label": "Your Details",      // optional display label
  "options": {
    "showPaper": true,           // card background (default false)
    "required": true,            // propagated to step schema required[]
    "variablePath": "Step1_pi", // auto-set by createStep()
    // ... block-specific options
  }
  // For Label (Paragraph) blocks only:
  // "text": "VwBlAGwAYwBvAG0AZQ=="  (top-level, base64 UTF-16LE)
}`}
      />
    </div>
  );
}
